# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main

    secrets:
      # This token is used to retrieve private repositories & to tag version
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      disable-version-bumping: false
